name: drinkable
description: A Flutter application which keeps track your water intake and remind you to drink water by sending notification.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  
  intl: ^0.16.1
  google_fonts: ^1.1.0
  provider: ^4.3.2+1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  cloud_firestore: ^0.14.0+2
  location: ^3.0.2
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets :
    - assets/icons/
    - assets/images/